mysql -u root -p${MYSQL_ROOT_PASSWORD} << EOF
CREATE DATABASE IF NOT EXISTS $ACE_IMS_DATABASE ;
CREATE USER "$ACE_IMSDBA_USER"@"%" IDENTIFIED BY "$ACE_IMSDBA_PASSWORD" ;
GRANT ALL ON $ACE_IMS_DATABASE.* TO "$ACE_IMSDBA_USER"@"%" ;
FLUSH PRIVILEGES ;
EOF
