#!/bin/bash
set -x

CREATE_SQL=/opt/ace-dbstore/ace-am.sql

mysql -v -u root -p${MYSQL_ROOT_PASSWORD} << EOF
CREATE DATABASE IF NOT EXISTS $ACE_IMS_DATABASE ;
CREATE USER "$ACE_IMSDBA_USER"@"%" IDENTIFIED BY "$ACE_IMSDBA_PASSWORD" ;
GRANT ALL ON $ACE_IMS_DATABASE.* TO "$ACE_IMSDBA_USER"@"%" ;
FLUSH PRIVILEGES ;
EOF

INDEX=$((1))
DBNAME="ACE${INDEX}_AM_DATABASE"

while [ "xx${!DBNAME}" != "xx" ]; do

  DBUSER="ACE${INDEX}_AMDBA_USER"
  DBPSWD="ACE${INDEX}_AMDBA_PASSWORD"
  
  mysql -v -u root -p${MYSQL_ROOT_PASSWORD} << EOF
CREATE DATABASE IF NOT EXISTS ${!DBNAME} ;
CREATE USER "${!DBUSER}"@"%" IDENTIFIED BY "${!DBPSWD}" ;
GRANT ALL ON ${!DBNAME}.* TO "${!DBUSER}"@"%" ;
FLUSH PRIVILEGES ;
EOF
  mysql -v -u ${!DBUSER} -p${!DBPSWD} ${!DBNAME} < $CREATE_SQL
  
  INDEX=$(($INDEX + 1))
  DBNAME="ACE${INDEX}_AM_DATABASE"
done
